In [1]:
import numpy as np
import cv2 as cv
cap = cv.VideoCapture('videoplayback.mp4')
# take first frame of the video
ret, frame = cap.read()
# setup initial location of window
x, y, width, height = 300, 200, 100, 50
track_window = (x, y ,width, height)
# set up the ROI for tracking
roi = frame[y:y+height, x : x+width]
hsv_roi = cv.cvtColor(roi, cv.COLOR_BGR2HSV)
mask = cv.inRange(hsv_roi, np.array((0., 60., 32.)), np.array((180., 255., 255)))
roi_hist = cv.calcHist([hsv_roi], [0], mask, [180], [0, 180])
cv.normalize(roi_hist, roi_hist, 0, 255,cv.NORM_MINMAX)
# Setup the termination criteria, either 10 iteration or move by atleast 1 pt
term_crit = ( cv.TERM_CRITERIA_EPS | cv.TERM_CRITERIA_COUNT, 10, 1)
cv.imshow('roi',roi)
while(1):
    ret, frame = cap.read()
    if ret == True:

        hsv = cv.cvtColor(frame, cv.COLOR_BGR2HSV)
        dst = cv.calcBackProject([hsv], [0], roi_hist, [0, 180], 1)
        # apply meanshift to get the new location
        ret, track_window = cv.CamShift(dst, track_window, term_crit)

        # Draw it on image
        pts = cv.boxPoints(ret)
        print(pts)
        pts = np.int0(pts)
        final_image = cv.polylines(frame, [pts], True, (0, 255, 0), 2)
        #x,y,w,h = track_window
        #final_image = cv.rectangle(frame, (x,y), (x+w, y+h), 255, 3)

        cv.imshow('dst', dst)
        cv.imshow('final_image',final_image)
        k = cv.waitKey(30) & 0xff
        if k == 27:
            break
    else:
        break

[[321.05795 195.11526]
 [388.5226  197.21301]
 [387.94205 215.88474]
 [320.4774  213.78699]]
[[323.6478  193.27504]
 [387.6708  198.46788]
 [386.3522  214.72496]
 [322.3292  209.53212]]
[[323.44406 194.86922]
 [389.67722 199.27538]
 [388.55594 216.13078]
 [322.32278 211.72462]]
[[320.3785  194.09752]
 [390.49387 197.64107]
 [389.6215  214.90248]
 [319.50613 211.35893]]
[[322.3669  196.82622]
 [387.16    198.92757]
 [386.6331  215.17378]
 [321.84    213.07243]]
[[321.4363  196.18953]
 [390.39383 200.07405]
 [389.5637  214.81047]
 [320.60617 210.92595]]
[[322.3336  197.84035]
 [391.22153 200.07912]
 [390.6664  217.15965]
 [321.77847 214.92088]]
[[321.34125 197.50832]
 [392.3969  200.86473]
 [391.65875 216.49168]
 [320.6031  213.13527]]
[[320.22787 197.47572]
 [395.50162 200.74901]
 [394.77213 217.52428]
 [319.49838 214.25099]]
[[323.71228 195.87706]
 [395.46667 200.39369]
 [394.28772 219.12294]
 [322.53333 214.60631]]
[[326.40817 197.40704]
 [395.46115 201.03168]
 [394.59183 217.59296]
 

[[354.0221  201.35298]
 [511.4995  203.04298]
 [510.9779  251.64702]
 [353.5005  249.95702]]
[[356.39093 201.89432]
 [517.23895 204.00049]
 [516.6091  252.10568]
 [355.76105 249.99951]]
[[354.43546 201.95901]
 [523.67175 205.7615 ]
 [522.5646  255.04099]
 [353.32825 251.2385 ]]
[[356.80936 198.96306]
 [529.086   205.41304]
 [527.1907  256.03693]
 [354.914   249.58696]]
[[357.90555 201.4834 ]
 [528.3894  202.50949]
 [528.0945  251.5166 ]
 [357.6106  250.49051]]
[[355.3142  201.22467]
 [531.0301  202.4263 ]
 [530.6858  252.77533]
 [354.9699  251.5737 ]]
[[356.3912  203.43167]
 [526.72784 200.32129]
 [527.60876 248.56833]
 [357.27216 251.67871]]
[[359.86017 201.868  ]
 [533.2347  202.19728]
 [533.13983 252.132  ]
 [359.76532 251.80272]]
[[358.77457 202.4562 ]
 [535.5196  200.03421]
 [536.22546 251.5438 ]
 [359.4804  253.96579]]
[[360.83344 200.39095]
 [538.0778  200.09709]
 [538.16656 253.60905]
 [360.92218 253.90291]]
[[363.1294  203.37485]
 [533.9428  197.10501]
 [535.8706  249.62515]
 

[[557.2477  345.66602]
 [609.1581  196.08215]
 [661.7523  214.33398]
 [609.8419  363.91785]]
[[562.6625  353.5573 ]
 [607.2959  201.19722]
 [659.3375  216.44269]
 [614.7041  368.8028 ]]
[[573.43854 362.30933]
 [606.18427 212.26024]
 [658.56146 223.69067]
 [625.81573 373.73975]]
[[578.6694  366.83224]
 [597.0157  229.384  ]
 [655.3306  237.16776]
 [636.9843  374.616  ]]
[[586.58325 361.78302]
 [603.00854 243.75844]
 [649.41675 250.21698]
 [632.99146 368.24158]]
[[593.0624  359.79913]
 [600.04004 259.0901 ]
 [644.9376  262.20087]
 [637.95996 362.9099 ]]
[[600.05865 348.94922]
 [607.7756  272.0216 ]
 [647.94135 276.05078]
 [640.2244  352.9784 ]]
[[642.09296 286.04813]
 [645.52936 346.94162]
 [609.90704 348.95187]
 [606.47064 288.05838]]
[[642.07135 285.09393]
 [642.21893 346.84326]
 [615.92865 346.90607]
 [615.78107 285.15674]]
[[642.3612  288.12372]
 [642.911   343.68555]
 [623.6388  343.87628]
 [623.089   288.31445]]
[[627.27893 344.0908 ]
 [627.2991  301.9028 ]
 [640.72107 301.9092 ]
 

[[513.61694 170.27968]
 [591.12134 167.76909]
 [592.38306 206.72032]
 [514.87866 209.23091]]
[[511.07724 167.11876]
 [589.6746  166.64583]
 [589.9227  207.88124]
 [511.32538 208.35417]]
[[511.39807 168.23654]
 [587.4038  166.00247]
 [588.6019  206.76346]
 [512.5962  208.99753]]
[[506.02896 171.39473]
 [585.6932  166.50371]
 [587.97107 203.60527]
 [508.30682 208.49629]]
[[507.65454 171.3947 ]
 [587.00806 166.28749]
 [589.34546 202.6053 ]
 [509.99194 207.71251]]
[[507.50104 170.69205]
 [586.1529  167.71747]
 [587.49896 203.30795]
 [508.8471  206.28253]]
[[505.42294 171.148  ]
 [584.46204 168.64479]
 [585.577   203.852  ]
 [506.53796 206.35521]]
[[504.28275 171.06499]
 [582.83356 166.73814]
 [584.7173  200.93501]
 [506.16644 205.26186]]
[[502.60098 168.62488]
 [579.78174 163.1922 ]
 [582.39905 200.37512]
 [505.21826 205.8078 ]]
[[502.1046  169.62595]
 [578.19495 161.90515]
 [581.8954  198.37405]
 [505.80505 206.09485]]
[[501.94467 167.58376]
 [576.3438  160.48988]
 [580.0553  199.41624]
 

[[488.17044  126.709816]
 [679.41144  222.83218 ]
 [611.8296   357.2902  ]
 [420.58856  261.16782 ]]
[[481.26218 127.37297]
 [679.7767  230.18443]
 [612.7378  359.627  ]
 [414.22333 256.81555]]
[[475.2144   126.197075]
 [677.9798   228.17319 ]
 [612.78564  357.80292 ]
 [410.0202   255.82681 ]]
[[470.70193 127.51915]
 [680.5553  230.2025 ]
 [617.2981  359.48083]
 [407.4447  256.7975 ]]
[[472.37668 124.76355]
 [686.10504 233.53925]
 [621.6233  360.23645]
 [407.89496 251.46075]]
[[473.20392 124.55795]
 [685.15424 221.56297]
 [624.7961  353.44205]
 [412.84576 256.437  ]]
[[473.9933  120.43798]
 [686.1875  207.09274]
 [628.0067  349.562  ]
 [415.8125  262.90726]]
[[489.58145 115.20891]
 [694.8188  223.22076]
 [622.4186  360.79108]
 [417.1812  252.77924]]
[[477.81522 115.06943]
 [677.05237 221.41866]
 [604.1848  357.93057]
 [404.94763 251.58134]]
[[437.19    104.37504]
 [672.42706 213.54776]
 [608.81    350.62497]
 [373.57294 241.45224]]
[[354.34238 117.85991]
 [620.0566  169.7682 ]
 [591.65

[[618.1228       0.98903084]
 [671.7781     227.50188   ]
 [483.8772     272.01096   ]
 [430.22192     45.498123  ]]
[[605.7202     -4.0946293]
 [676.55994   217.93799  ]
 [494.2798    276.09464  ]
 [423.44006    54.06201  ]]
[[579.2391   -11.110172]
 [690.9205   194.8347  ]
 [520.7609   287.11017 ]
 [409.07953   81.1653  ]]
[[562.6454     -2.8707428]
 [689.55444   182.99973  ]
 [540.3546    284.87073  ]
 [413.44556    99.000275 ]]
[[557.88257   13.577541]
 [675.631    187.19424 ]
 [541.11743  278.42245 ]
 [423.36902  104.805756]]
[[549.9955   35.74951]
 [670.0254  184.4314 ]
 [560.0045  273.2505 ]
 [439.9746  124.5686 ]]
[[553.65845  55.10044]
 [667.13934 179.53369]
 [571.34155 266.89957]
 [457.86066 142.46631]]
[[535.5334    76.530334]
 [664.2839   157.86224 ]
 [599.4666   260.46967 ]
 [470.71613  179.13776 ]]
[[510.80234 108.44037]
 [656.02563 137.51022]
 [635.19763 241.55963]
 [489.97437 212.48978]]
[[505.5701  110.79821]
 [656.2013  133.48474]
 [640.42993 238.20178]
 [489.7987  21

[[323.52118 -88.70624]
 [716.5302   94.59002]
 [598.4788  347.70624]
 [205.46979 164.40997]]
[[327.797   -87.68373]
 [722.6521   95.84521]
 [604.203   350.68372]
 [209.3479  167.15479]]
[[343.78928 -85.68107]
 [724.19794 107.1882 ]
 [598.2107  355.68106]
 [217.80206 162.8118 ]]
[[355.80157 -79.36218]
 [722.6281  115.11194]
 [594.1984  357.36218]
 [227.37189 162.88806]]
[[364.66763 -69.2441 ]
 [718.5736  122.98569]
 [591.3324  357.2441 ]
 [237.42639 165.01431]]
[[367.36142 -51.8609 ]
 [713.8173  127.43582]
 [596.63855 353.8609 ]
 [250.18268 174.56418]]
[[377.69345 -37.23108]
 [712.9713  139.52878]
 [600.3065  353.23108]
 [265.0287  176.47122]]
[[3.9792380e+02 5.9178162e-01]
 [6.9885974e+02 1.4326292e+02]
 [6.0207617e+02 3.4740820e+02]
 [3.0114026e+02 2.0473708e+02]]
[[407.59952   58.738182]
 [673.47546  126.82952 ]
 [622.4005   326.2618  ]
 [356.52454  258.17047 ]]
[[391.62805 126.95974]
 [634.6646   95.26299]
 [658.37195 277.04025]
 [415.3354  308.737  ]]
[[393.5253  189.74916]
 [624.2

 [639.4864    238.19899  ]]
[[517.95      233.69879  ]
 [537.86395    -3.9379878]
 [660.05        6.3012085]
 [640.13605   243.93799  ]]
[[518.61005   225.63728  ]
 [539.36395    -4.4630327]
 [659.38995     6.3627167]
 [638.63605   236.46303  ]]
[[520.68036   229.8574   ]
 [536.1192     -2.896748 ]
 [657.31964     5.1425934]
 [641.8808    237.89674  ]]
[[517.31665   221.03828  ]
 [540.1022     -5.374489 ]
 [662.68335     6.9617157]
 [639.8978    233.37448  ]]
[[520.9983    217.14314  ]
 [539.03955    -3.932837 ]
 [659.0017      5.8568573]
 [640.96045   226.93283  ]]
[[515.0664    210.56952  ]
 [541.18933    -6.0124135]
 [660.9336      8.430481 ]
 [634.81067   225.01242  ]]
[[511.11353   206.96892  ]
 [539.2717     -7.2198553]
 [662.8865      9.031082 ]
 [634.7283    223.21985  ]]
[[514.62726   212.00381  ]
 [534.9759     -4.6855216]
 [659.37274     6.9961853]
 [639.0241    223.68552  ]]
[[513.93585   211.1773   ]
 [534.02094    -4.8937316]
 [660.06415     6.822693 ]
 [639.97906   222.8

[[-43.29614   25.067505]
 [665.1709   -23.339844]
 [683.29614  241.9325  ]
 [-25.170898 290.33984 ]]
[[-42.37727   23.210922]
 [665.59735  -21.415382]
 [682.37726  244.78908 ]
 [-25.597351 289.41537 ]]
[[-42.94423   24.699799]
 [665.068    -23.005737]
 [682.9442   242.3002  ]
 [-25.067993 290.00574 ]]
[[-42.890476  23.90068 ]
 [665.68054  -21.936996]
 [682.8905   244.09932 ]
 [-25.680542 289.937   ]]
[[-44.20847   23.991013]
 [666.8595   -22.03273 ]
 [684.2085   246.00899 ]
 [-26.859497 292.0327  ]]
[[-43.82054   28.939774]
 [662.30774  -27.256493]
 [683.82056  243.06023 ]
 [-22.30774  299.2565  ]]
[[-41.906296  24.422638]
 [663.7353   -22.822266]
 [681.9063   248.57736 ]
 [-23.73529  295.82227 ]]
[[-43.38151   26.752335]
 [663.3072   -25.138779]
 [683.38153  248.24767 ]
 [-23.30719  300.1388  ]]
[[-43.88031   26.727646]
 [663.7598   -25.155258]
 [683.8803   249.27235 ]
 [-23.759827 301.15527 ]]
[[-46.878242  28.978409]
 [665.37634  -26.756798]
 [686.87823  248.02159 ]
 [-25.376343 303

[[-41.61151   -8.829514]
 [693.1871    10.332352]
 [685.6115   300.82953 ]
 [-49.187073 281.66766 ]]
[[-42.527813  -9.514084]
 [696.8334    11.594223]
 [688.52783  302.5141  ]
 [-50.833374 281.40576 ]]
[[-39.79506  -13.27861 ]
 [699.1478    15.36113 ]
 [687.79504  308.27863 ]
 [-51.147827 279.63885 ]]
[[-41.06486   -9.698959]
 [703.49475   11.883713]
 [695.0649   302.69897 ]
 [-49.49475  281.11627 ]]
[[-23.158628 -20.48117 ]
 [704.1344    22.547455]
 [687.1586   309.48117 ]
 [-40.1344   266.45255 ]]
[[ 14.985679  -20.35167  ]
 [700.81354    22.327072 ]
 [683.01434   308.35168  ]
 [ -2.8135376 265.6729   ]]
[[ 41.110714 -32.208313]
 [701.2007    34.637146]
 [672.8893   314.2083  ]
 [ 12.799316 247.36285 ]]
[[ 50.673355 -33.309357]
 [700.51074   35.105835]
 [671.32666  312.30936 ]
 [ 21.489258 243.89417 ]]


KeyboardInterrupt: 